const appname = "ABC Store";
const appversion = "Version 1.0.0";
const credits = "@Flutter Lads";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Flutter Lads";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Term And Conditions";
const alreadyHaveAccount = "Already have an account?";
//home strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
